### ISSUE TITLE
cannot add keys to a hot wallet

### ISSUE THREAD

**Issue by djpnewton** [cryptoadvance/specter-desktop#1103]
When restoring a wallet from backup that includes a bitcoind hot wallet one is unable to add keys to the hot wallet because the hot wallet does not exist in bitcoind (only as metadata in specter)

The workaround is to first restore the hot wallet from the bip39 words and after that restore the specter wallet from backup

**Comment by djpnewton** [comment]
this is related to #948

**Comment by k9ert** [comment]
And might get addressed in #1109

**Comment by k9ert** [comment]
#1109 is merged. I'm closing this here, feel free to reopen if it's still not solved.

**Comment by kdmukai** [comment]
#1109 wasn't merged. It's still a DRAFT PR. It consists of two parts: adding device type and description info to wallet backups (merged as a separate PR: #1226) and the actual restoring of hot wallets.

#1109 is still not complete because at the time the UI/js code was too difficult to alter.

I haven't had a chance to revisit this since those pages have been revised.

So I'm reopening this ticket and leaving #1109 in its DRAFT state; the eventual solution should be based on that PR but when the time comes, it'll be easier to close #1109 and submit a separate, clean hot wallet restoration PR.

**Comment by k9ert** [comment]
In the meantime #1495 was merged. I'm not sure how this is related to #1109 but at least this issue is fixed now.
