### ISSUE TITLE
Price not updating: Failed to fetch data...

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#1554]
No matter who I select as a price provider it stopped working (even before the latest 1.8.1 release).

![Screenshot from 2022-02-03 16-03-14](https://user-images.githubusercontent.com/68573637/152437003-b4153228-1985-43cd-a9ac-f3d4b06bdd15.png)

**Comment by k9ert** [comment]
I just tested it via specterd on Linux and it works there. What platform are you running on?

**Comment by BTCBellyButton** [comment]
@k9ert Linux Ubuntu 20.04.

**Comment by BTCBellyButton** [comment]
![Screenshot from 2022-02-04 14-18-39](https://user-images.githubusercontent.com/68573637/152597607-bff4cf16-6ad0-49b5-96b0-aab53d76daa7.png)

**Comment by BTCBellyButton** [comment]
[2022-02-04 14:41:44,889] INFO in checker: Checker price started with period 600
[2022-02-04 14:41:47,525] WARNING in price_providers: Failed to get price data from: spotbit_kraken. Exception: SOCKSHTTPConnectionPool(host='h6zwwkcivy2hjys6xpinlnz2f74dsmvltzsd4xb42vinhlcaoe7fdeqd.onion', port=80): Max retries exceeded with url: /now/usd/kraken (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7ff5a460b760>: Failed to establish a new connection: 0x01: General SOCKS server failure'))
[2022-02-04 14:41:47,526] INFO in checker: Checker executed within 2.637 seconds. This message won't show again until stopped and started.
[2022-02-04 14:41:49,045] WARNING in price_providers: Failed to get price data from: spotbit_kraken. Exception: SOCKSHTTPConnectionPool(host='h6zwwkcivy2hjys6xpinlnz2f74dsmvltzsd4xb42vinhlcaoe7fdeqd.onion', port=80): Max retries exceeded with url: /now/usd/kraken (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7ff5a460b250>: Failed to establish a new connection: 0x01: General SOCKS server failure'))
[2022-02-04 14:41:49,045] INFO in _internal: 192.168.1.22 - - [04/Feb/2022 14:41:49] "POST /price/update/ HTTP/1.1" 200 -

**Comment by moneymanolis** [comment]
Looks like a Tor issue.

**Comment by k9ert** [comment]
Closing this for now. Tor is sometimes not that stable. Would still be interesting whether it's fixed in the meantime?!

**Comment by k9ert** [comment]
Closing this for now. Tor is sometimes not that stable. Would still be interesting whether it's fixed in the meantime?!

**Comment by BTCBellyButton** [comment]
Nope. Still not working.  :(

**Comment by BTCBellyButton** [comment]
More log data:

[2022-03-05 20:24:31,071] INFO in checker: Checker price started with period 600
[2022-03-05 20:24:32,131] WARNING in price_providers: Failed to get price data from: bitstamp. Exception: Expecting value: line 1 column 1 (char 0)
[2022-03-05 20:24:32,133] INFO in _internal: 192.168.1.22 - - [05/Mar/2022 20:24:32] "POST /price/update/ HTTP/1.1" 200 -
[2022-03-05 20:24:32,271] WARNING in price_providers: Failed to get price data from: bitstamp. Exception: Expecting value: line 1 column 1 (char 0)
[2022-03-05 20:24:32,272] INFO in checker: Checker executed within 1.203 seconds. This message won't show again until stopped and started.

**Comment by BTCBellyButton** [comment]
I just tried the 1.9.0 and it still does not work  :(


[2022-03-31 16:28:03,151] ERROR in specter_error: Unexpected error:
[2022-03-31 16:28:03,151] ERROR in specter_error: ----START-TRACEBACK-----------------------------------------------------------------
[2022-03-31 16:28:03,151] ERROR in specter_error: Error as json doesn't look reasonable: 'kraken'
Traceback (most recent call last):
  File "/home/go/.local/lib/python3.8/site-packages/cryptoadvance/specter/util/price_providers.py", line 129, in get_price_at
    currency_symbol = currency_mapping[currency]["symbol"]
KeyError: 'kraken'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/go/.local/lib/python3.8/site-packages/cryptoadvance/specter/util/price_providers.py", line 101, in update_price
    price, symbol = get_price_at(specter, timestamp="now")
  File "/home/go/.local/lib/python3.8/site-packages/cryptoadvance/specter/util/price_providers.py", line 195, in get_price_at
    raise SpecterError(f"Error as json doesn't look reasonable: {ke}")
cryptoadvance.specter.specter_error.SpecterError: Error as json doesn't look reasonable: 'kraken'
[2022-03-31 16:28:03,151] ERROR in specter_error: ----END---TRACEBACK-----------------------------------------------------------------

**Comment by k9ert** [comment]
I agree, that there are issues. I assume that tor is part of the problem. I've created https://github.com/cryptoadvance/specter-desktop/pull/1640 which should at least fix the issue (ALSO and especially for historical prices) with non-tor use.
Unfortunately i forgot to merge the issue for `v1.9.0` but `v1.9.1` is coming this weekend or monday latest!
I'll hopefully also try to find some time to look into tor-issues but i have the suspicion that Tor use might be increasingly difficult. E.g. i checked with Bitstamp and for some reason i get a [403](https://http.cat/403) when accessing the very same url over tor which works over clearnet.

**Comment by BTCBellyButton** [comment]
Just installed the 1.9.1.

I get a 403 too:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.bitstamp.net/api/v2/ticker/btcusd

But if I paste that URL in my browser it works fine.
In the tor browser (Brave) this is the message:

> 
> Access Denied
> Error 15
> www.bitstamp.net
> 2022-04-02 20:38:09 UTC
> What happened?
> This request was blocked by the security rules
> Your IP: 89.234.157.254
> Proxy IP: 107.154.248.133 (ID 101194-100)
> Incident ID: 1194000050185016652-476419346171298125

So I think Bitstamp don't like the traffic from TOR? 

With Kraken this is my log:

> 22-04-02 15:27:04,698] INFO in _internal: 192.168.1.22 - - [02/Apr/2022 15:27:04] "^[[37mPOST /price/update/ HTTP/1.1^[[0m" 200 -
> [2022-04-02 15:29:43,903] ERROR in specter_error: Unexpected error:
> [2022-04-02 15:29:43,903] ERROR in specter_error: ----START-TRACEBACK-----------------------------------------------------------------
> [2022-04-02 15:29:43,903] ERROR in specter_error: Error as json doesn't look reasonable: 'kraken'
> Traceback (most recent call last):
>   File "/home/go/.local/lib/python3.8/site-packages/cryptoadvance/specter/util/price_providers.py", line 129, in get_price_at
>     currency_symbol = currency_mapping[currency]["symbol"]
> KeyError: 'kraken'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/go/.local/lib/python3.8/site-packages/cryptoadvance/specter/util/price_providers.py", line 101, in update_price
>     price, symbol = get_price_at(specter, timestamp="now")
>   File "/home/go/.local/lib/python3.8/site-packages/cryptoadvance/specter/util/price_providers.py", line 195, in get_price_at
>     raise SpecterError(f"Error as json doesn't look reasonable: {ke}")
> cryptoadvance.specter.specter_error.SpecterError: Error as json doesn't look reasonable: 'kraken'
> [2022-04-02 15:29:43,903] ERROR in specter_error: ----END---TRACEBACK-----------------------------------------------------------------
> [2022-04-02 15:29:43,904] INFO in _internal: 192.168.1.22 - - [02/Apr/2022 15:29:43] "^[[37mPOST /price/update/ HTTP/1.1^[[0m" 200 -

**Comment by k9ert** [comment]
Sorry for the late answer. Yes, i agree, bitstamp API doesn't like tor-traffic. I did some additional stuff on a later `v1.9.x` version and recommend an update. It's still not perfect especially because we don't give detailed enough guidance on all the edge-cases.
As we don't have enough time for this, we need to stick to the happy path, though.
